Adding the files for release update
GSS-Cogs/csvcubed-models pull request #15
Opened 2023-07-06 13:12 UTC by nimshi89

2023-07-06 14:15 UTC, robons requested changes

2023-07-06 14:15 UTC, roblinksdata commented on .github/workflows/release.yaml
> +  Trigger_gss-utils_workflow:
This can't be here.

2023-07-06 14:15 UTC, roblinksdata commented on .github/workflows/release.yaml
> +  build_package_and_documentation:
Rename because there is no documentation. Watch out for the references in the `if` and `needs` statements.

2023-07-06 14:15 UTC, roblinksdata commented on .github/workflows/release.yaml
> +          - os: ubuntu-latest
Remove please.

2023-07-06 14:15 UTC, roblinksdata commented on .github/workflows/release.yaml
> +  publish_package_and_documentation:
Rename since no documentation.

2023-07-06 14:15 UTC, roblinksdata commented on .github/workflows/reusable-deploy.yaml
> +name: Deploy csvcubed whl and documentation
Change the name since no documentation and this is csvcubed-models not csvcubed.

2023-07-06 14:15 UTC, roblinksdata commented on .github/workflows/reusable-deploy.yaml
> +  publish_package_and_documentation:
Change name, no docs.

2023-07-06 14:15 UTC, roblinksdata commented on .github/workflows/reusable-deploy.yaml
> +          name: package-and-documentation
Rename artifact (needs to be done in the reusable-build.yaml too).

2023-07-06 14:15 UTC, roblinksdata commented on .github/workflows/reusable-deploy.yaml
> +          password: ${{ secrets.PYPI_API_TOKEN }}
Please check whether TEST_PYPIAPI_TOKEN and PYPI_API_TOKEN secrets exist in this repo.

2023-07-06 14:15 UTC, roblinksdata commented on .github/workflows/reusable-deploy.yaml
> +      - name: Publish Docs
This step needs to go. There are no docs to publish.

2023-07-06 14:15 UTC, roblinksdata commented on .github/workflows/reusable-release_gssutils.yaml
> +name: Trigger csvcubed update in gss-utils
Remove this file please.

2023-07-06 14:15 UTC, roblinksdata commented on .github/workflows/reusable-test.yaml
> +name: Test csvcubed
Change name since csvcubed-models.

2023-07-06 14:15 UTC, roblinksdata commented on .github/workflows/reusable-test.yaml
> +      - uses: ruby/setup-ruby@v1
Can you alter this so that it'll only run on ubuntu (not windows) and use the `gsscogs/pythonversiontesting` docker image as the build environment. This'll massively speed the build up and reduce the amount of complexity in this file. You won't need to install much at all.

2023-07-06 14:15 UTC, roblinksdata commented on .github/workflows/reusable-test.yaml
> +      - uses: ruby/setup-ruby@v1
Follow the pattern of using gsscogs/pythonversiontesting [here](https://github.com/GSS-Cogs/csvcubed-pmd/blob/main/.github/workflows/dev.yaml#L16C14-L16C42).

Note you won't have to install python/pyright/etc. anymore.

2023-07-07 11:07 UTC, robons submitted a review, later dismissed

2023-07-07 11:07 UTC, robons commented on .github/workflows/release.yaml
> +        os: [ubuntu-latest, windows-latest]
Don't we need to remove windows from this list? I thought it was only going to work under ubuntu?

2023-07-07 11:07 UTC, robons commented on .github/workflows/reusable-test.yaml
> +on:
Why does this have a trigger and a strategy? It's not reusable anymore.

2023-07-07 11:07 UTC, robons commented on .github/workflows/reusable-test.yaml
> +        uses: docker/login-action@v1
This shouldn't be published to docker hub. Why is this here?

2023-07-07 11:07 UTC, robons commented on .github/workflows/reusable-test.yaml
> +            gsscogs/pmdutils:latest
This definitely shouldn't be done.

2023-07-07 11:07 UTC, robons commented on .github/workflows/release.yaml
> +      os: ${{ matrix.os }}
This workflow no longer accepts any inputs.

2023-07-07 11:07 UTC, robons commented on .github/workflows/release.yaml
> +    if: needs.test_in_environments.result == 'success'
This is going to be run concurrently with `reuseable-test.yaml` since it has its own triggers.

2023-07-10 09:11 UTC, rossbowen commented
Charlie asked me to resolve comments and dismiss the outstanding review.

2023-07-10 14:00 UTC, NickPapONS approved these changes
I believe the requested changes have been satisfied, and I have no other changes to request so I will give approval. Though I do recommend someone more experienced with workflow files to have a look to be sure.

2023-07-10 14:14 UTC, merged